export const DOCK_APP_ICON_DATA_TOOLTIP_DELAY_SHOW = 150;

export const TERMINAL_WINDOW_CHECK_ICON_SIZE = 20;
export const TERMINAL_WINDOW_FLAG_ICON_SIZE = 15;

export const RESUME_WINDOW_PDF_PAGE_NUMBER = 1;
